# Generated by Django 4.2.25 on 2026-06-12 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('agriculture', '🌱 農業・園芸系'), ('manufacturing', '🔧 製造・組み立て系'), ('cleaning', '🧹 清掃・環境整備系'), ('food_processing', '🍱 食品加工系'), ('service', '🛒 接客・販売補助系')], max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('job_type',)},
            },
        ),
        migrations.CreateModel(
            name='GrowthStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('step_number', models.IntegerField(choices=[(1, 'ステップ1：生活習慣・基礎スキル'), (2, 'ステップ2：作業スキル'), (3, 'ステップ3：就労準備')], verbose_name='ステップ番号')),
                ('job_type', models.CharField(blank=True, choices=[('agriculture', '🌱 農業・園芸系'), ('manufacturing', '🔧 製造・組み立て系'), ('cleaning', '🧹 清掃・環境整備系'), ('food_processing', '🍱 食品加工系'), ('service', '🛒 接客・販売補助系')], max_length=30, verbose_name='仕事タイプ')),
                ('category', models.CharField(max_length=50, verbose_name='カテゴリ')),
                ('content', models.TextField(verbose_name='タスク内容')),
                ('daily_action', models.TextField(blank=True, verbose_name='今日できる小さな行動')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step_number', 'id'],
            },
        ),
    ]
