# Generated by Django 4.2.25 on 2026-05-26 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('learning', '学習・スキル'), ('character', '人間性・心の成長'), ('habit', '日々の習慣'), ('social', 'コミュニケーション'), ('strength', '強みを活かす活動')], max_length=20)),
                ('content', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='accounts.childprofile')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('score', models.IntegerField(choices=[(1, '😢 とてもつらい'), (2, '😟 すこしつらい'), (3, '😐 ふつう'), (4, '😊 まあまあ'), (5, '😄 とてもよい')])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to='accounts.childprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
