# Generated by Django 4.2.25 on 2026-06-12 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('did_well', models.TextField(blank=True, verbose_name='できたこと')),
                ('struggled_with', models.TextField(blank=True, verbose_name='むずかしかったこと')),
                ('emotion_stamp', models.IntegerField(choices=[(5, '😄 とてもよい'), (4, '😊 まあまあ'), (3, '😐 ふつう'), (2, '😟 すこしつらい'), (1, '😢 とてもつらい')], default=3, verbose_name='きもち')),
                ('health_score', models.IntegerField(choices=[(3, '💪 からだがよい'), (2, '😌 ふつう'), (1, '🤒 つらい')], default=2, verbose_name='からだのようす')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
