# Generated by Django 4.2.25 on 2026-06-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar_config'),
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
