# Generated by Django 4.2.25 on 2026-05-26 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='ニックネーム')),
                ('career_goal', models.CharField(blank=True, max_length=50, verbose_name='目標の職業')),
                ('career_goal_name', models.CharField(blank=True, max_length=100, verbose_name='職業名')),
                ('age_group', models.CharField(choices=[('early_childhood', '幼少期（3〜6歳）'), ('lower_elementary', '小学校低学年（7〜9歳）'), ('upper_elementary', '小学校高学年（10〜12歳）'), ('middle_school', '中学生（13〜15歳）'), ('high_school', '高校生（16〜18歳）'), ('adult', '大学・社会人（19歳〜）')], default='lower_elementary', max_length=30, verbose_name='年齢フェーズ')),
                ('total_points', models.IntegerField(default=0, verbose_name='合計ポイント')),
                ('badges', models.TextField(default='[]', verbose_name='バッジ')),
                ('avatar_emoji', models.CharField(default='🌟', max_length=10, verbose_name='アバター絵文字')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='accounts.childprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
