# Generated by Django 4.2.25 on 2026-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='アバター設定'),
        ),
    ]
