# Generated by Django 5.0b1 on 2026-07-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('', '---'), ('elementary_low', '小学生（低学年）'), ('elementary_high', '小学生（高学年）'), ('junior_high', '中学生'), ('high_school', '高校生')], default='', max_length=20, verbose_name='学年区分'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('adult', '就労を目指す大人'), ('child', '児童')], default='adult', max_length=10, verbose_name='利用者種別'),
        ),
    ]
