# Generated by Django 6.1 on 2026-08-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_desired_career_userprofile_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_type_preference',
            field=models.CharField(blank=True, default='', help_text='diagnosis の job_type が自動セットされる', max_length=30, verbose_name='診断で判定された職業タイプ'),
        ),
    ]
