# Generated by Django 5.0b1 on 2026-07-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_grade_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desired_career',
            field=models.CharField(blank=True, choices=[('', '未選択'), ('doctor', '医師・看護師'), ('teacher', '先生・保育士'), ('engineer', 'エンジニア・プログラマー'), ('artist', '絵・デザイン・音楽'), ('sports', 'スポーツ選手'), ('chef', '料理人・パティシエ'), ('police', '警察官・消防士'), ('vet', '獣医・動物関係'), ('other', 'まだ決まっていない')], default='', max_length=20, verbose_name='なりたい職業'),
        ),
    ]
