# Generated by Django 6.1 on 2026-08-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_desired_career_userprofile_grade_and_more'),
        ('accounts', '0004_userprofile_desired_career'),
    ]

    operations = [
    ]
