# Generated by Django 6.1 on 2026-08-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_job_type_preference'),
        ('accounts', '0005_merge_20260810_1214'),
    ]

    operations = [
    ]
