# Generated by Django 6.1 on 2026-08-19 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daycare', '0003_child_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MannerQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('greeting', '挨拶・言葉遣い'), ('report', '報連相'), ('manner', 'ビジネスマナー'), ('safety', '安全・衛生'), ('team', 'チームワーク')], max_length=20, verbose_name='カテゴリ')),
                ('question', models.TextField(verbose_name='問題文')),
                ('emoji', models.CharField(default='❓', max_length=10, verbose_name='絵文字')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
                ('order', models.IntegerField(default=0, verbose_name='順番')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='本のタイトル')),
                ('comment', models.TextField(blank=True, verbose_name='ひとこと感想')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐')], default=3, verbose_name='評価')),
                ('read_at', models.DateField(verbose_name='読んだ日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='対象日')),
                ('mood', models.IntegerField(choices=[(5, 'とても良かった'), (4, '良かった'), (3, '普通'), (2, '少し心配'), (1, '心配')], default=3, verbose_name='今日のようす')),
                ('content', models.TextField(verbose_name='連絡内容')),
                ('homework', models.TextField(blank=True, verbose_name='おうちでやってほしいこと')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_sent', to=settings.AUTH_USER_MODEL)),
                ('target_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_notes', to='daycare.child')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='テンプレート名')),
                ('day_of_week', models.IntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], default=0, verbose_name='曜日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=10, verbose_name='質問ID')),
                ('answer', models.TextField(verbose_name='回答')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AIフィードバック')),
                ('practiced_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_practices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-practiced_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='選択肢')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('order', models.IntegerField(default=0, verbose_name='順番')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.mannerquiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10, verbose_name='時刻')),
                ('activity', models.CharField(max_length=100, verbose_name='活動名')),
                ('emoji', models.CharField(default='📍', max_length=10, verbose_name='絵文字')),
                ('color', models.CharField(default='green', max_length=20, verbose_name='色')),
                ('order', models.IntegerField(default=0, verbose_name='順番')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.dailyscheduletemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StampEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_type', models.CharField(max_length=20, verbose_name='スタンプ種別')),
                ('stamp_emoji', models.CharField(default='⭐', max_length=10, verbose_name='絵文字')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='メモ')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='得意なこと・できたこと')),
                ('emoji', models.CharField(default='⭐', max_length=10, verbose_name='絵文字')),
                ('date', models.DateField(verbose_name='日付')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.mannerquiz')),
                ('selected_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.quizchoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
    ]
