# Generated by Django 5.0b1 on 2026-08-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_userprofile_desired_career'),
        ('daycare', '0003_child_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRecordEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='daycare.supportrecord')),
            ],
            options={
                'verbose_name': '支援記録埋め込み',
                'verbose_name_plural': '支援記録埋め込み一覧',
            },
        ),
        migrations.CreateModel(
            name='UserProfileEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': '利用者埋め込み',
                'verbose_name_plural': '利用者埋め込み一覧',
            },
        ),
    ]
