# Generated by Django 4.2.25 on 2026-06-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('answers', models.TextField(default='{}')),
                ('focus_score', models.IntegerField(default=0, verbose_name='集中力')),
                ('communication_score', models.IntegerField(default=0, verbose_name='コミュニケーション力')),
                ('endurance_score', models.IntegerField(default=0, verbose_name='体力・持続力')),
                ('accuracy_score', models.IntegerField(default=0, verbose_name='几帳面さ・正確性')),
                ('emotion_control_score', models.IntegerField(default=0, verbose_name='感情コントロール')),
                ('learning_score', models.IntegerField(default=0, verbose_name='学習意欲・変化への適応')),
                ('job_type', models.CharField(blank=True, choices=[('agriculture', '🌱 農業・園芸系'), ('manufacturing', '🔧 製造・組み立て系'), ('cleaning', '🧹 清掃・環境整備系'), ('food_processing', '🍱 食品加工系'), ('service', '🛒 接客・販売補助系')], max_length=30, verbose_name='向いている仕事タイプ')),
                ('result_strengths', models.TextField(default='[]')),
                ('result_challenges', models.TextField(default='[]')),
                ('result_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
