# Generated by Django 6.1 on 2026-08-19 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.CharField(max_length=200, verbose_name='説明')),
                ('emoji', models.CharField(default='🎯', max_length=10, verbose_name='絵文字')),
                ('target_type', models.CharField(max_length=20, verbose_name='種類')),
                ('target_count', models.IntegerField(default=3, verbose_name='目標数')),
                ('reward_points', models.IntegerField(default=100, verbose_name='報酬ポイント')),
                ('week_number', models.IntegerField(default=1, verbose_name='週番号')),
            ],
        ),
        migrations.CreateModel(
            name='CheerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('emoji', models.CharField(default='💪', max_length=10, verbose_name='絵文字')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='実習先名')),
                ('date', models.DateField(verbose_name='実習日')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='実習時間')),
                ('work_content', models.TextField(verbose_name='作業内容')),
                ('good_points', models.TextField(blank=True, verbose_name='良かったこと')),
                ('challenges', models.TextField(blank=True, verbose_name='課題・気になったこと')),
                ('staff_comment', models.TextField(blank=True, verbose_name='支援員コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='ポイント')),
                ('reason', models.CharField(max_length=100, verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_key', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results_gami', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, verbose_name='現在の連続日数')),
                ('max_streak', models.IntegerField(default=0, verbose_name='最長連続日数')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='最後のアクティブ日')),
                ('total_points', models.IntegerField(default=0, verbose_name='累計ポイント')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=30, verbose_name='称号キー')),
                ('title_name', models.CharField(max_length=50, verbose_name='称号名')),
                ('description', models.CharField(max_length=100, verbose_name='説明')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=False, verbose_name='表示中')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title_key')},
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='進捗')),
                ('completed', models.BooleanField(default=False, verbose_name='完了')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.weeklychallenge')),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
